services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: false
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      TZ: Europe/Berlin
    networks:
      - blackhole

networks:
  blackhole:
    external: true

