services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/:/config
      - /mnt/nextcloud-data:/data
    restart: unless-stopped
    networks:
      - blackhole

networks:
  blackhole:
    external: true
